### ISSUE TITLE
Getting timeout

### ISSUE THREAD

**Issue by robinwolny** [NETWAYS/check_cloud_aws#4]
Hi, I have an issue when running command with huge ASG (+3000) EC2 instances.
```
[root@icinga02-xxx plugins]# ./check_cloud_aws ec2 instances -n xxx
UNKNOWN - Timeout reached
[root@icinga02-xxx plugins]#
````

**Comment by pdorschner** [comment]
Hi robinwolny,
was the problem solved or why did you close the issue? For a better approach, you could check all instances in a specific region, e.g.:

`./check_cloud_aws ec2 instances -n xxx -R eu-central-1`

**Comment by robinwolny** [comment]
Hi Philipp, I'm sorry ... was struggling with timeout. It works fine however we have a huge ASG with dynamic schedule (EC2 are almost always going up & down) in one region. So I have to evaluate a number of running instances in ASG and current ASG schedule. This can be probably done via your tool and Icinga aws module (variable asg_desired_size).

**Comment by lazyfrosch** [comment]
The problem at the moment would be, that we query InstanceStatus for each instance individually.

Maybe we can refactor this to perform the same query as for Instances, then we would 2 bulk queries.

Open question is still, how effective the plugin is against such a long list of instances. The output should be tuned to at least only list problems then.
